server:
  port: 8080
---
spring:
  cloud:
    gateway:
      routes:
        - id: google
          uri: http://google.com
          predicates:
            - Path=/google/{param}
          filters:
            - RewritePath=/google(?<segment>/?.*),/search
            - AddRequestParameter=q,{param}
        - id: facebook
          uri: http://facebook.com
          predicates:
            - Path=/groups

        - id: product
          uri: http://localhost:10000
          predicates:
            - Path=/product/**,,/products/**,/goods/**
        # - id: order
        #   uri: http://localhost:8081
        #   predicates:
        #     - Path=/orders/**
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - '*'
          allowedMethods:
            - '*'
          allowedHeaders:
            - '*'
          allowCredentials: true